### ISSUE TITLE
trait.Hasher

### ISSUE THREAD

**Issue by nbari** [oconnor663/blake2_simd#18]
Could method `update` be renamed to `write` and finalize to `finish` besides returning `u64` instead of `Hash` to satisfy the `Trait std::hash::Hasher` https://doc.rust-lang.org/std/hash/trait.Hasher.html

**Comment by oconnor663** [comment]
Forgive me if this was already clear, but you may be misunderstanding how Rust traits work. They're not like Go, where using the right method names and types means you automatically implement an interface. Instead, you explicitly write an `impl` block for each trait you want to implement, with all the required methods defined in that block.

So, changing the name of `update` to `write` wouldn't really make a difference for implementing the `Hasher` trait. We'd still need an explicit `impl std::hash::Hasher for Hasher` block, with its own `write` method in there.

That said, implementing `std::hash::Hasher` might not be a good idea. That trait is intended for use with HashMaps and similar data structures. There, the output is designed to be short (64 bits) and collisions are tolerable. Cryptographic hash functions like BLAKE2 are different. Collisions are not tolerable, so the output has to be at least 256 bits. And because of other security requirements, they're usually substantially slower.

**Comment by nbari** [comment]
Thanks for the explanation and for the "very fast" implementation of BLAKE2.  I am currently testing different libraries and indeed came up with a none cryptographic hash (xxHash) that implements the trait `Hasher` and confused me, but now is more clear.

In my current use case, I want to check for duplicates files and to be "safe" regarding collisions I decided to go for `BLAKE2bp`. for testing I am using something similar to what you have here: https://github.com/oconnor663/blake2_simd/blob/master/blake2_bin/src/main.rs#L157 but wonder how could I speed up the process mainly when dealing with big files (like 4GB for example), if possible could you please explain more about the comment:  "we're_ going to use --mmap and skip buffering entirely" or how to achieve this within rust?

**Comment by oconnor663** [comment]
You might want to benchmark BLAKE2sp in addition to BLAKE2bp. This is counterintuitive, but BLAKE2sp is usually slightly faster on long inputs.

Memory mapping is an OS feature where you can say "please pretend that this file lives in memory, and every time I read or write the corresponding memory pages, please actually do file IO for me under the covers." The real advantage of memory mapping is when your OS already has a given file cached in memory. In that case, it can just map the relevant memory pages directly into your process's address space, and then you can read the file without making any system calls and without doing any extra copying. (You can see that happening here: https://github.com/oconnor663/blake2_simd/blob/master/blake2_bin/src/main.rs#L333-L334.) That can be a measurable performance advantage in some cases. But it's also possible for it to hurt performance, particularly for small files. This is a somewhat complicated topic, so the standard advice applies: you'll need to write benchmarks that simulate your own use case and see if the performance goes up or down.

**Comment by oconnor663** [comment]
If you want to go really nuts, you can play with benchmarking my experimental [Bao hash](https://github.com/oconnor663/bao/) for your use case. There memory mapping really helps, because having all the input (probably) in memory lets us split it all up with [Rayon](https://github.com/rayon-rs/rayon) and multi-thread the whole thing. I'd be very curious if you have a use case that actually benefits from this. Usually you need to have _really_ long files before it genuinely starts to matter. Unfortunately Bao is not yet stable, so you shouldn't ship production software using it today.

**Comment by nbari** [comment]
Many thanks for the example and suggestion about `BLAKE2sp`,  because of the **s** I thought that was only for 8- to 32-bit platforms but if I am understanding can be run fine in amd64 right?

**Comment by oconnor663** [comment]
Yes that's exactly what's confusing. I should clarify that all the BLAKE2 variants perform fine on almost any architecture. If you look at [the benchmarks in my repo](https://github.com/oconnor663/blake2_simd#performance), you'll see that BLAKE2s runs at about 2/3 the speed of BLAKE2b, which is a hardly noticeable difference in most applications. A similar relationship applies when you try to run BLAKE2b on a 32-bit system; it's slower, but usually not dramatically slower.

The reason that BLAKE2sp actually performs slightly better than BLAKE2bp on 64-bit systems with SIMD is tricky. The way SIMD gets used, BLAKE2sp is hashing 8 blocks in parallel, while BLAKE2bp is hashing 4 blocks in parallel. It turns out that that means they're both using 256-bit vectors, and the 256-bit vector instructions for e.g. adding 8 32-bit ints or 4 64-bit ints perform exactly the same. Then the biggest remaining difference is that BLAKE2bp (like BLAKE2b) has an output size that's twice as large, so it does slightly more work (12 rounds instead of 10) to mix everything thoroughly.

**Comment by nbari** [comment]
Many thanks for the explanations and keep up the good work 👍
